// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5KdGG_BxS4EnGfc8Y3XHWTymjF_7fs_Q',
    appId: '1:119873014013:web:57b269331c1689089c5694',
    messagingSenderId: '119873014013',
    projectId: 'ui-parenting-app',
    authDomain: 'ui-parenting-app.firebaseapp.com',
    storageBucket: 'ui-parenting-app.appspot.com',
    measurementId: 'G-KXNKLT3TY1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGxwZRISljFnhgcumZVl342SI7ULTUqxE',
    appId: '1:119873014013:android:3af82b5790fa24a29c5694',
    messagingSenderId: '119873014013',
    projectId: 'ui-parenting-app',
    storageBucket: 'ui-parenting-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOQA1rryzfxjDIQBwWxTzvMiDW7qReQoU',
    appId: '1:119873014013:ios:6623af45a61ae29e9c5694',
    messagingSenderId: '119873014013',
    projectId: 'ui-parenting-app',
    storageBucket: 'ui-parenting-app.appspot.com',
    iosBundleId: 'com.example.concuatuiAppclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOQA1rryzfxjDIQBwWxTzvMiDW7qReQoU',
    appId: '1:119873014013:ios:6623af45a61ae29e9c5694',
    messagingSenderId: '119873014013',
    projectId: 'ui-parenting-app',
    storageBucket: 'ui-parenting-app.appspot.com',
    iosBundleId: 'com.example.concuatuiAppclone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5KdGG_BxS4EnGfc8Y3XHWTymjF_7fs_Q',
    appId: '1:119873014013:web:f3b849f3599b850f9c5694',
    messagingSenderId: '119873014013',
    projectId: 'ui-parenting-app',
    authDomain: 'ui-parenting-app.firebaseapp.com',
    storageBucket: 'ui-parenting-app.appspot.com',
    measurementId: 'G-8M5GN84KD7',
  );
}
